# Generated by Django 4.1.1 on 2023-10-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_medico_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recepcionista',
        ),
    ]
