# Generated by Django 4.2.5 on 2023-10-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('especie_mascota', models.CharField(max_length=20)),
                ('raza_mascota', models.CharField(max_length=20)),
                ('edad_mascota', models.IntegerField()),
                ('nombre_dueno', models.CharField(max_length=20)),
                ('rut_dueno', models.TextField(max_length=20)),
            ],
        ),
    ]
