# Generated by Django 4.1.1 on 2023-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='rut_dueno',
            field=models.CharField(max_length=20),
        ),
    ]
