# Generated by Django 4.1.1 on 2023-10-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_cita_con_medico_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita_con_medico',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
